; COLOR EXPLANATION
; main, sidebar, player = background
; card                  = cards, tracklist, dropdowns, input fields
; shadow                = text on button, tab active & selected row
; selected row          = selected song & tab
; button-active         = play button, outline on focused input
; button                = all other buttons
; button-disabled       = volume & seekbar background, scrollbar handle, borders, hover



[Base]
; Red on dark grey background
text               = e00000
subtext            = ffffff
button-text        = ffffff
main               = 101010
sidebar            = 171717
player             = 171717
subbutton-text     = 101010
card               = 171717
shadow             = 6d1414
selected-row       = 330d0d
sub-button         = a20606
button             = e00000
button-active      = e00000
button-disabled    = 404040
tab-active         = 171717
notification       = 5e0000
notification-error = 5e0000
playback-bar       = ff4700
misc               = adadad